enabled: true
agent:
  name: copilot-coding-agent
  allow:
    - paths: ["src/**/*", "tests/**/*", "README.md", "AGENTS.md"]
      actions: ["create", "modify", "delete"]
  require_review_before_merge: true
  required_approvals: 1
  allowed_merge_strategies:
    - squash
    - merge
  auto_merge_on_green: false
  run_workflows: true
notes: |
  - This manifest expresses the policy for the Copilot coding agent in this repository.
  - It does NOT install or authorize the agent; a repository admin must install the Copilot coding agent app and grant the repository the necessary permissions (contents: write, pull_requests: write, checks: write, actions: write/read, issues: write) to allow the agent to act.
  - Keep allow paths narrow and prefer require_review_before_merge during initial rollout.
